server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:acc
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: create