routes:
  accounts:
    url: http://localhost:8081/accounts
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mb
    username: user
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: create