POST http://localhost:8080/registration
Content-Type: application/json

{"password": "pass", "firstName": "El", "lastName": "Bo", "passportNum": "834212"}

###
DELETE http://localhost:8080/delete?id=1

###
DELETE http://localhost:8080/delete?id=4

###
POST http://localhost:8080/update
Content-Type: application/json

{"password": "update", "firstName": "El", "lastName": "Bo", "passportNum": "834212"}